const alertsLookup = {
  16: "Total Odometer",
  21: "GSM Signal",
  31: "Engine Load",
  32: "Coolant Temperature",
  36: "Engine RPM",
  37: "Vehicle Speed",
  42: "Runtime since engine start",
  43: "Distance Traveled MIL On",
  45: "Direct Fuel Rail Pressure",
  48: "Fuel Level",
  57: "Hybrid battery pack life",
  58: "Engine Oil Temperature",
  59: "Fuel injection timing",
  60: "Fuel Rate",
  66: "External Voltage",
  67: "Battery Voltage",
  68: "Battery Current",
  69: "GNSS Status",
  81: "Vehicle Speed",
  82: "Accelerator Pedal Position",
  83: "Fuel Consumed",
  113: "Battery Level",
  181: "GNSS PDOP",
  182: "GNSS HDOP",
  200: "Sleep Mode",
  236: "Alarm",
  239: "Ignition",
  240: "Movement",
  241: "Active GSM Operator",
  246: "Towing",
  247: "Crash detection",
  249: "Jamming",
  252: "Unplug",
  254: "Green Driving Value",
  258: "EcoMaximum",
  259: "EcoAverage",
  283: "Driving State",
  284: "Driving Records",
  389: "OBD OEM Total Mileage",
  390: "OBD OEM Fuel Level",
  85: "Engine RPM",
  87: "Total Millage",
  89: "Fuel Level",
  100: "Program Number",
  105: "Total Millage ()",
  107: "Fuel Consumption",
  115: "Engine Temperature",
  207: "RFID"
};

export const alertsDecoder = key => {
  return alertsLookup[key];
};
